/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.appreactor.adivinarnumero;

import java.awt.event.KeyEvent;
import java.util.Random;

/**
 *
 * @author Lord_Nightmare
 */
public class Principal extends javax.swing.JFrame {

    private int numero;
    private int intentos;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        lblResultado.setText("");
        setLocationRelativeTo(null);
        bgNivel.add(rbFacil);
        bgNivel.add(rbDificil);
        lblIntentos.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgNivel = new javax.swing.ButtonGroup();
        txtValor = new javax.swing.JTextField();
        btnIntentar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        rbFacil = new javax.swing.JRadioButton();
        rbDificil = new javax.swing.JRadioButton();
        btnRendirse = new javax.swing.JButton();
        lblIntentos = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorKeyTyped(evt);
            }
        });

        btnIntentar.setText("Intentar");
        btnIntentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntentarActionPerformed(evt);
            }
        });

        btnNuevo.setText("Nuevo Juego");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        lblTitulo.setText("Adivina el Numero");

        rbFacil.setText("Facil (2 digitos)");

        rbDificil.setText("Dificil (4 digitos)");

        btnRendirse.setText("Rendirse");
        btnRendirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRendirseActionPerformed(evt);
            }
        });

        lblIntentos.setText("Te quedan {n} intentos");

        lblResultado.setText("valNumber");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIntentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtValor)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 169, Short.MAX_VALUE)
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRendirse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIntentar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbFacil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbDificil))
                            .addComponent(lblResultado))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(10, 10, 10)
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbFacil)
                    .addComponent(rbDificil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIntentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIntentar)
                    .addComponent(btnNuevo)
                    .addComponent(btnRendirse))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIntentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntentarActionPerformed
        if (intentos > 0) {
            evaluarIntento();
        }
        if (intentos <= 0) {
            lblIntentos.setText("Has agotado tu numero de intentos, buena suerte para la proxima");
            btnNuevo.setEnabled(true);
            btnIntentar.setEnabled(false);
            btnRendirse.setEnabled(false);
        }
    }//GEN-LAST:event_btnIntentarActionPerformed

    private void btnRendirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRendirseActionPerformed
        btnNuevo.setEnabled(true);
        btnIntentar.setEnabled(false);
        btnRendirse.setEnabled(false);
        lblResultado.setText("El numero a adivinar era: " + numero);
        lblIntentos.setText("Descuida, no todos pueden ser triunfadores");
    }//GEN-LAST:event_btnRendirseActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        txtValor.setText("");
        this.obtenerNuevoNumero();
        System.out.println("numero: " + numero);
        this.intentos = 6;
        lblIntentos.setText("Te quedan " + intentos + " intentos");
        btnNuevo.setEnabled(false);
        btnRendirse.setEnabled(true);
        btnIntentar.setEnabled(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyTyped
        char caracter = evt.getKeyChar();
        if (!Character.isDigit(caracter) || (caracter == KeyEvent.VK_BACK_SPACE) || (caracter == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtValorKeyTyped

    private void obtenerNuevoNumero() {
        if (rbDificil.isSelected()) {
            numero = this.generarNumeroDificil();
            return;
        }
        numero = this.generarNumeroFacil();
    }

    private void evaluarIntento() {
        int valor = Integer.parseInt(txtValor.getText());
        if (valor == numero) {
            lblResultado.setText("Felicidades el numero ingresado es el correcto");
            btnNuevo.setEnabled(true);
            btnIntentar.setEnabled(false);
            btnRendirse.setEnabled(false);
            return;
        }
        if (valor > numero || valor < numero) {
            lblResultado.setText("El numero ingresado es " + (valor > numero ? "mayor" : "menor") + " que el esperado");
            intentos--;
            lblIntentos.setText("Te quedan " + intentos + " intentos");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    private int generarNumeroFacil() {
        return new Random().nextInt(99 - 10 + 1) + 10;
    }

    private int generarNumeroDificil() {
        return new Random().nextInt(9999 - 1000 + 1) + 1000;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgNivel;
    private javax.swing.JButton btnIntentar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRendirse;
    private javax.swing.JLabel lblIntentos;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbDificil;
    private javax.swing.JRadioButton rbFacil;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
